# /*******************************************************************************
#  * Copyright 2023 Intel Corporation.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  * in compliance with the License. You may obtain a copy of the License at
#  *
#  * http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software distributed under the License
#  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  * or implied. See the License for the specific language governing permissions and limitations under
#  * the License.
#  *
#  *******************************************************************************/

version: '3.7'

services:
  rtsp-server:
    image: aler9/rtsp-simple-server:${RTSP_SERVER_VERSION}
    ports:
      - "127.0.0.1:8554:8554/tcp"
    container_name: edgex-rtsp-server
    hostname: edgex-rtsp-server
    read_only: true
    restart: always
    networks:
      - edgex-network
    security_opt:
      - no-new-privileges:true
    environment:
      MTX_RTMPDISABLE: yes
      MTX_HLSDISABLE: yes
      MTX_WEBRTCDISABLE: yes
      MTX_PROTOCOLS: tcp
      MTX_EXTERNALAUTHENTICATIONURL: http://edgex-device-usb-camera:8000/rtspauth
    user: "${EDGEX_USER}:${EDGEX_GROUP}"
